### ISSUE TITLE
Passing server-side request data into Transmit

### ISSUE THREAD

**Issue by Azaeres** [RickWong/react-transmit#11]
Let's say we have a React component that presents user info as a function of an access token.  The client stuffs that access token into a cookie.  For isomorphic consistency it would be nice to be able to set up a Transmit query that results in that access token, so that when we render we can just get `this.props.accessToken`.

In a naive experiment I patched `react-transmit` to pass through some details of the request, but I wanted to ask you if there was a way to do this without a patch.

``` javascript
/**
 * Catch dynamic requests here to fire-up React Router.
 */
server.ext("onPreResponse", (request, reply) => {
    if (typeof request.response.statusCode !== "undefined") {
        return reply.continue();
    }

    Router.run(routes, request.path, (Handler, router) => {

        // Unpack request data.  <-----------------------------------------------------
        const { state, query } = request;

        Transmit.renderToString(
            Handler,

            {},

            // Pass the request data into `renderToString()` somehow?  <------------------
            { queryParams: { state: state, query: query } }

        ).then(({reactString, reactData}) => {
            let output = (
                `<!doctype html>
                <html lang="en-us">
                    <head>
                        <meta charset="utf-8">
                        <title>CyberU</title>
                        <link rel="shortcut icon" href="/favicon.ico">
                    </head>
                    <body>
                        <div id="react-root">${reactString}</div>
                    </body>
                </html>`
            );

            const webserver = process.env.NODE_ENV === "production" ? "" : "//localhost:8080";
            output = Transmit.injectIntoMarkup(output, reactData, [`${webserver}/dist/client.js`]);

            reply(output);
        }).catch((error) => {
            reply(error.stack).type("text/plain").code(500);
        });
    })
});
```

We can then write a Transmit query like:

``` javascript
export default Transmit.createContainer(Main, {
  queries: {
    accessToken (queryParams) {
      return new Promise((resolve, reject) => {
        const token = queryParams.state && queryParams.state.access_token || '';
        resolve(token);
      })
    }
  }
});
```

Does this make any sense?  What is the best way to do this kind of thing?

**Comment by RickWong** [comment]
Hmm... On second thought, actually I think this already works without patching `setQueryParams`. Have you tried passing `queryParams` as normal prop as the **second argument of** `Transmit.renderToString`?

**Comment by Azaeres** [comment]
I had tried the following with an older version of Transmit, which didn't work without a patch:

``` javascript
const { state, query } = request;
Transmit.renderToString(
    Handler,
    { queryParams: { state: state, query: query } }
)
```

But just now I tried it with an _unpatched_ Transmit v2.5.4, and it worked, so that's cool.  Thanks again!

**Comment by RickWong** [comment]
Cool! Thanks for reporting back. BTW in ES6 you can write it with this Object literal shorthand: `{queryParams: {state, query}}`. The variables will be extracted as key-value combinations automatically!
