### ISSUE TITLE
Support isomorphic environments, don't rely on component state

### ISSUE THREAD

**Issue by RickWong** [RickWong/react-transmit#2]
Currently the container uses `this.state` and `this.setState()` to store the resolved data. It should store the data elsewhere so isomorphic apps can 1) resolve the data before rendering, 2) pass the resolved data onto the client.

**Comment by jackmoore** [comment]
Did you change your mind?

**Comment by RickWong** [comment]
Should've closed with a message. This issue has been implemented! Check out the latest release 2.0.0 and react-isomorphic-starterkit for the isomorphic usage of Transmit (renderToString()).
