### ISSUE TITLE
Remove __reactTransmitPacket after client side render

### ISSUE THREAD

**Issue by ericfong** [RickWong/react-transmit#21]
I use HistoryLocation with react-router with server-rendering. 
In order to prevent, using the same window.__reactTransmitPacket for the same route all the time.

Shall we add

```
if (window.__reactTransmitPacket) delete window.__reactTransmitPacket
```

after
https://github.com/RickWong/react-transmit/blob/master/src/lib/render.js#L15

**Comment by RickWong** [comment]
Thanks Eric, this sounds good. Are there any isomorphic cases where Transmit should not clear the whole packet even though HistoryLocation is used? Maybe things like big country lists and session data.

So what I'm wondering is, should clearing be done: always after first render / optional for other pages / manually?

**Comment by ericfong** [comment]
I think should always done after first render. Like loading ajax data.

If they want to keep the data, store somewhere manually.

I think that is the expected behaviour.

**Comment by RickWong** [comment]
Thanks. Will implement and release this soon.

**Comment by RickWong** [comment]
Implemented.
