### ISSUE TITLE
Allow user to configure which Promise implementation to use

### ISSUE THREAD

**Issue by XeeD** [RickWong/react-transmit#27]
Related to #26 

@RickWong 

> Yes, I believe that should work. Although on second thought, we should expose this feature with a more explicit API:

``` js
import Bluebird from 'bluebird';
import Transmit from 'react-transmit';

Transmit.setPromiseLibrary(Bluebird);
```

**Comment by ooflorent** [comment]
Not sure about the naming. `usePromiseConstructor` is more descriptive since `Promise` is not a library.

``` js
Transmit.setPromiseLibrary(Promise)     // odd
Transmit.usePromiseConstructor(Promise) // better, ihmo
```

**Comment by RickWong** [comment]
Valid concern. How's `Transmit.setPromiseImplementation(Bluebird)` ?

**Comment by XeeD** [comment]
I would like `setPromiseConstructor` most, but all mentioned names are fine with me.

**Comment by ericfong** [comment]
assume es6?

**Comment by RickWong** [comment]
@ericfong This is going to be optional. Assuming ES6 in global scope, but freedom to override within Transmit's scope.

**Comment by RickWong** [comment]
Implemented.
