### ISSUE TITLE
switch between /posts/1 and posts/2 will not trigger queries

### ISSUE THREAD

**Issue by lilee** [RickWong/react-transmit#31]
because /posts/1 and /posts/2 route to the same handler, so `componentWillMount` can not be invoked. React Only invoke `render` function.

I think react-transimit should implement `componentWillReceiveProps` method, like

``` javascript
componentWillReceiveProps: function(nextProps) {
    var needToLoad = !shallowEqual(
        nextProps.queryParams,
        this.props.queryParams
    );
    if (needToLoad) {
        this.setQueryParams(nextProps.queryParams);
    }
}
```

the new react-router implements the similar function https://github.com/rackt/react-router/blob/master/modules/experimental/AsyncProps.js#L40

**Comment by RickWong** [comment]
Thanks for reporting this, @lilee.

**Comment by lilee** [comment]
I submit the Pull Request
