### ISSUE TITLE
Support optional deferred props (and spinner components)

### ISSUE THREAD

**Issue by RickWong** [RickWong/react-transmit#32]
Apparently Relay now specifies a defer feature that allows some of the props to not be required but optional (on first render). This means that the way Transmit used to work a long time ago, was actually correct. Spinners and other while-loading components are simply declared within if-else blocks. 

![screen shot 2015-07-02 at 19 12 04](https://cloud.githubusercontent.com/assets/40102/8483072/4317a492-20ee-11e5-8fd2-284880bc130f.png)

![screen shot 2015-07-02 at 19 15 45](https://cloud.githubusercontent.com/assets/40102/8483122/c382ff0a-20ee-11e5-8bcc-9273b788440b.png)

**Comment by RickWong** [comment]
A Transmit implementation would either require adding a custom `Promise.defer()` method to the Promise definition to tell Transmit to defer resolving the query... or much simpler without screwing with Promise definitions: add a `getQueryDeferred()` method. 

For the example from the screen captures above:

``` js
   CommentList.getQueryDeferred("comments")
```

**Comment by nicib83** [comment]
Building a wrapper component to separate dependences as an alternative approach
