### ISSUE TITLE
Option to compose queries before sending them

### ISSUE THREAD

**Issue by brysgo** [RickWong/react-transmit#34]
Can we have `getQuery` pass a query param so we have the option to return the query string instead of the query response?

```
myQuery (queryParams) {
  let query = ...
  if (queryParams.prefetch) {
    return Promise.resolve(query);
  } else {
    return fetchQuery(query);
  }
}
```

**Comment by RickWong** [comment]
Is this something you cannot solve outside of Transmit? You need to know what type of information is resolved anyways, so for example by returning a small wrapper object `{ type: "querystring", data }` vs. `{ type: "queryresult", data }` instead of just the data.

**Comment by brysgo** [comment]
yeah, I'll do it that way to keep things simple.
