### ISSUE TITLE
Use something other than string indexing to access queries?

### ISSUE THREAD

**Issue by tejacques** [RickWong/react-transmit#37]
Using the example on the README, I don't see a reason why this:

``` .js
Story.getQuery("story", {storyId: 1})
```

Couldn't be done like this:

``` .js
Story.queries.story({storyId: 1})
```

This has two upsides:
1. Clear object query hierarchy (this makes tooling like autocomplete much easier)
2. No magic string arguments passed to a function

**Comment by RickWong** [comment]
Hi @tejacques when I created React Transmit I tried to follow Relay's API as much as I could, so switching to Relay would be really easy. 

Although I agree that magic strings are error prone, I don't want to stray from Relay's API. However this idea could perhaps better be implemented as a helper, as a secondary facade-like API.

**Comment by tejacques** [comment]
@RickWong I didn't realize this was the official Relay API (I haven't been able to find anything about it -- where did FB release it?), but that makes sense now. Acting as a secondary API makes sense to me -- thanks for looking into it!
