### ISSUE TITLE
What about Relay?

### ISSUE THREAD

**Issue by RickWong** [RickWong/react-transmit#38]
- [Relay](https://facebook.github.io/relay/) was released today
- Its APIs have [changed](https://facebook.github.io/relay/docs/api-reference-relay-container.html#content), [dramatically](https://facebook.github.io/relay/docs/api-reference-relay.html#content)
- Its Network Layer [abstraction](https://facebook.github.io/relay/docs/interfaces-relay-network-layer.html#content) might support Promises

**Comment by broveloper** [comment]
@RickWong, What does this mean for react-transmit?

**Comment by RickWong** [comment]
I'll probably update the API naming to mimic Relay again. Perhaps add their "Root Container" concept too. However I won't be adding GraphQL-specific stuff.

But first let's wait and see how Relay evolves. It's still "just" a tech preview right?

**Comment by broveloper** [comment]
I agree, still a tech preview.  I just hope they don't keep renaming, it'll get harder to maintain projects like react-transmit.  Thanks bro, really appreciate your thoughtfulness and efforts.

**Comment by RickWong** [comment]
I've updated the naming to resemble the official API. Relay's mutations and other cool features will be explored individually.
