### ISSUE TITLE
(React Router) ScrollBehavior not works

### ISSUE THREAD

**Issue by lilee** [RickWong/react-transmit#4]
render return null and then render the real component, ScrollBehavior not works

**Comment by RickWong** [comment]
Hmm right. Thanks for reporting this! Any idea how this can be fixed? Easiest way is to set a min-height on your component. But there must be a way to relay the query data for the first render.

**Comment by RickWong** [comment]
Hey @lilee I've just released version react-transmit@2.2.1 with the new `getAllQueries()` method. You should be able to transition to a route, injecting all the query results like this:

``` js

    onLinkClicked (event) {
        event.preventDefault();

        // Page.getAllQueries() returns a Promise with the query results.
        Page.getAllQueries({count: +1}).then((queryResults) => {
            // When the query results are in, then transition to a route passing
            // queryResults as route params.
            this.context.router.transitionTo("PageRoute", {queryResults});
        });
    },
```

Let me know whether this solves your issue.

**Comment by lilee** [comment]
@RickWong Thanks, but it works not well with the bootstrap router handler, like the "Home" handler

**Comment by RickWong** [comment]
What do you mean by "not well"? Can you perhaps point it out in a few lines of code?

As for the bootstrap Home handler, that one does not need scroll behavior yet, right?

**Comment by lilee** [comment]
@RickWong goBack() to the Home page need scroll behavior

**Comment by RickWong** [comment]
@lilee You should be able to implement caching yourself by specifying the `onQueryComplete()` callback on the Homepage, and remembering the query results in localstorage or a flux-store. Upon going back to Homepage, you populate the Homepage using the remembered data. https://github.com/RickWong/react-transmit/blob/61d3301a88376837ae0f8f9854a8a27975acaacd/src/example/Main.js#L61

**Comment by lilee** [comment]
Thanks, now it works well with the PageCache.

``` javascript
render() {
  var name = this.context.router.getCurrentPath();
  var cache = PageCache.get(name) || {};
  var props = assign({}, this.props || {}, cache, {
    onQueryComplete: this._onQueryComplete.bind(this)
  });
  return <Page {..props} />;
}
// ...

_onQueryComplete(error, result) {
 var name = this.context.router.getCurrentPath();
 if (error) {
   return;
 }
 PageCache.set(name, result);
}
```

**Comment by RickWong** [comment]
That's nice! Thanks for reporting back your solution.

**Comment by RickWong** [comment]
@lilee Note that in `react-transmit@2.5.0` I renamed `onQueryComplete(error, result)` to `onQuery(promise)` and you get a promise to work with. 

https://github.com/RickWong/react-transmit/blob/master/src/example.js#L6-L10
