### ISSUE TITLE
(Transmit) Accessing router parameters for initial load

### ISSUE THREAD

**Issue by withgallantry** [RickWong/react-transmit#40]
Hi,
I have a search page that takes it's query from the URL. Is there a way to set the initial variable for react-transmit? Currently it loads with a generic query, which brings back all results and then the client takes over and renders the query taken from the URL. I've done this using code that access the routers on the componentWillMount. Is there another way? I've read all the documentation and can't seem to work it out other  than by using stores which is a bit overkill for what I want to currently do.

**Comment by RickWong** [comment]
I assume you mean server-side rendering. There are two options here:

1) Set initialVariables in static time. This might not work if you've already required/imported the component file earlier.

2) Pass variables to the component in run time like this `<Container variables={params} />`. That is merged into the initialVariables, so the fragment can use `params` for the initial fetch. Docs: https://github.com/RickWong/react-transmit/blob/master/DOCS.md#variables--object
