### ISSUE TITLE
Uncaught Error: Only root Transmit Containers should fetch fragments

### ISSUE THREAD

**Issue by broveloper** [RickWong/react-transmit#46]
After updating from 3.0.8 > 3.1.2, I received this error.

Uncaught Error: Only root Transmit Containers should fetch fragments

My temporary solution was to add the { initialVariables: {} } as an option in my Transmit.createContainer process.

Is it a requirement to have initialVariables: {} in Transmit.createContainer?

**Comment by RickWong** [comment]
It might be a bug. I'll look into it. Thanks.
