### ISSUE TITLE
Omit initialVariables render nothing

### ISSUE THREAD

**Issue by gutenye** [RickWong/react-transmit#49]
Given

```
Transmit.createContainer(App, {
  // initialVariables: {}  // without it
  fragements: { ... }
})
```

The page does not render anything, nor any errors.

**Comment by RickWong** [comment]
I really need to document this somewhere. Containers with `initialVariables` are so-called "root containers" and their fragments are fetched at start. Containers without `initialVariables` will never be automatically fetched. It's by design.

**Comment by ghost** [comment]
Is this concept of "root containers" new with version three of Transmit? Have its definition and requirements been documented yet? Thank you.
