### ISSUE TITLE
setQueryParams() fires all of queries

### ISSUE THREAD

**Issue by lilee** [RickWong/react-transmit#5]
I have 3 queries in Container. When I invoke setQueryParams, I want to fire one of these queries. But setQueryParams fires all of these

**Comment by RickWong** [comment]
Honestly, I'm not sure how Facebook's own Relay handles this. I do think I've got a solution, by adding an optional `queryName` argument to `setQueryParams()`, but I will need to verify whether it's a clean solution.

**Comment by RickWong** [comment]
@lilee You can now use `this.props.setQueryParams(..., "query_name");` to fire only 1 of the queries.

Available at `react-transmit@2.3.2`

**Comment by tsunammis** [comment]
@RickWong why this issue have been reopened ?

**Comment by RickWong** [comment]
@tsunammis Just waiting for @lilee's feedback.

**Comment by tsunammis** [comment]
Ok, thank you ;-)

**Comment by RickWong** [comment]
Ok closing this issue. Assuming fix is sufficient.

**Comment by lilee** [comment]
`this.props.setQueryParams(..., "query_name")`

I think it would be better if `query_name` can be string array

**Comment by RickWong** [comment]
@lilee That's implemented now.
