### ISSUE TITLE
How to pass additonal data to react components not defined as fragments?

### ISSUE THREAD

**Issue by tmadison-gpsw** [RickWong/react-transmit#58]
I would like to pass additional data to the transmit containers so that it can be accessed via 'this.props.foo' but not actually be defined as a fragment...as we only need to pass this data once on the server to the client...Thanks!

**Comment by tmadison-gpsw** [comment]
Closing as you can manually assign additional variables to the reactData array in server.js

**Comment by kulikalov** [comment]
@tmadison-gpsw, could you tell more on how do you use this? 
I assume, you are pushing additional objects into `reactData` at 
```
Transmit.renderToString(ReactRouter.RouterContext, renderProps).then(({reactString, reactData}) => {
```
but then what?
