### ISSUE TITLE
ReadMe issues

### ISSUE THREAD

**Issue by winkler1** [RickWong/react-transmit#8]
Hi-
 Looking at the docs and trying to follow the control flow...feels like the docs don't really address it. The example does not make a lot of sense without the right introduction IMO.

Suggestions-
- Docs should mention that it's higher order component
- control flow…how are params passed in?
- CSS being first in examples files is confusing/distracting, takes up ~ first 25 lines. Example: https://github.com/RickWong/react-transmit/blob/master/src/example/Main.js Maybe export all to another JS file and import? 

IMO, the docs would benefit from a simple example...perhaps with two components... explaining the connections, params and data flow between them. Thanks!

**Comment by RickWong** [comment]
Already made an issue for documenting the APIs: https://github.com/RickWong/react-transmit/issues/3 

Thanks for all the good suggestions. In the meantime if you have any questions, just ask!

**Comment by RickWong** [comment]
@winkler1 How's this? https://github.com/RickWong/react-transmit/blob/master/DOCS.md

Also updated the README and the example files.

**Comment by winkler1** [comment]
mmm, feels a bit like a wall of text to me. Have not seen the "ah, I get it" example that makes me grok why it's worthwhile. What's the shortest somewhat realistic example with a couple components?

Seems like this stuff is non-visual, but the equivalent of a screenshot: something people can glance at quickly and understand the benefit.

**Comment by RickWong** [comment]
Thanks, will add some visuals. Agree that visuals are important to understand the big picture.

Maybe get inspired by the diagrams on http://facebook.github.io/react/blog/2015/03/19/building-the-facebook-news-feed-with-relay.html
